version: '3.8'

services:
  # FastAPI 應用服務
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: smartmoney-api
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URI_Solana}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/1}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/1}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - WALLET_ANALYSIS_TOPIC=${WALLET_ANALYSIS_TOPIC:-wallet_analysis_tasks}
      - API_TITLE=SmartMoney API
      - API_DESCRIPTION=智能錢包分析API
      - API_VERSION=1.0.0
      - API_PREFIX=/api
      - DB_ENABLED=true
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - SECRET_KEY=${SECRET_KEY:-change_this_to_a_secure_random_string}
      - API_KEYS=${API_KEYS:-test_api_key_1,test_api_key_2}
      - SOLSCAN_API_TOKEN=${SOLSCAN_API_TOKEN}
      - SOLSCAN_API_URL=${SOLSCAN_API_URL:-https://pro-api.solscan.io/v2.0}
      - WALLET_SYNC_API_ENDPOINT=${WALLET_SYNC_API_ENDPOINT}
      - MAX_CONCURRENT_REQUESTS=100
      - MAX_ADDRESSES_PER_REQUEST=300
      - MAX_WORKER_PROCESSES=5
      - CACHE_TTL_SECONDS=3600
      - LOG_FILE=/app/logs/api.log

    volumes:
      - ./:/app
      - ./app/logs:/app/logs
    networks:
      - smartmoney-network
    command: python run.py

  # Redis 服務 - 用於快取和消息佇列
  redis:
    image: redis:6.2-alpine
    container_name: smartmoney-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smartmoney-network

  # PostgreSQL 數據庫
  db:
    image: postgres:13-alpine
    container_name: smartmoney-db
    restart: always
    environment:
      - POSTGRES_USER=test_pg01_rwuser01
      - POSTGRES_PASSWORD=E2#dN4c6d5Mz
      - POSTGRES_DB=smart_money
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smartmoney-network

volumes:
  redis-data:
  postgres-data:

networks:
  smartmoney-network:
    driver: bridge